---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  labels:
    app: apicurio-registry
spec:
  replicas: REGISTRY_REPLICAS
  selector:
    matchLabels:
      name: registry
  template:
    metadata:
      labels:
        app: apicurio-registry
        name: registry
    spec:
      containers:
        - name: apicurio-registry
          image: quay.io/apicurio/apicurio-registry-sql:2.0.0.Final
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: AUTH_ENABLED
              value: "false"
            - name: REGISTRY_ENABLE_MULTITENANCY
              value: "false"
            - name: REGISTRY_LOG_LEVEL
              value: DEBUG
            - name: LOG_LEVEL
              value: DEBUG
            - name: QUARKUS_PROFILE
              value: prod
            - name: REGISTRY_DATASOURCE_URL
              value: jdbc:postgresql://RDS_HOST:RDS_PORT/RDS_DB
            - name: REGISTRY_DATASOURCE_USERNAME
              value: RDS_USER
            - name: REGISTRY_DATASOURCE_PASSWORD
              value: RDS_PASS
            - name: QUARKUS_DATASOURCE_JDBC_MAX-SIZE
              value: "200"
          resources:
            limits:
              cpu: "4"
              memory: 12Gi
            requests:
              cpu: "1"
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
  strategy:
    type: Recreate
---
# Services for the components
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio-registry
    template: apicurio-registry
  name: apicurio-registry
spec:
  selector:
    app: apicurio-registry
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
status:
  loadBalancer: {}
---
# Routes
apiVersion: v1
kind: Route
metadata:
  name: apicurio-registry
  labels:
    app: apicurio-registry
    template: apicurio-registry
spec:
  to:
    kind: Service
    name: apicurio-registry
    weight: 100
  wildcardPolicy: None
---
