apiVersion: v1
kind: Namespace
metadata:
  name:  registry-monitoring
  labels:
    app: registry-monitoring
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: registry-monitoring
  namespace: registry-monitoring
spec:
  targetNamespaces:
  - registry-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: registry-monitoring
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.47.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: registry-monitoring
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v3.10.0