apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: registry-monitoring
  labels:
    app: registry-monitoring
    system: registry-perftest
spec:
  namespaceSelector:
    matchNames:
      - apicurio-registry-sql
  selector:
    matchLabels:
      app: apicurio-registry
  endpoints:
    - path: /metrics
      interval: 30s